plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://judging-machine.github.io
baseurl: /gemini

title: Judging Machine
description: This is a machine that reasons.

machine:
  name: Judging-Machine
  verb: Judging
  instructions_file: judging.txt
  token: gemini.txt
  apiUrl: https://generativelanguage.googleapis.com/v1beta/models/

app:
  worker_name: gemapi.js

lm:
  model: gemini-2.5-pro
  maxOutputTokens: 65536
  temperature: 1.0
  topP: 0.9
  topK: 50
  thinkingBudget: 32768
  includeThoughts: true


github_settings:
  owner: judging-machine
  repo: judging_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
